Repository data-driven-forms/react-form-renderer, pull requests merged in 2018-12, with the labels that each got.

#8 Added configurable form buttons.
  src/form-renderer/form-controls.js
  src/form-renderer/index.js
  src/tests/form-renderer/__snapshots__/form-controls.test.js.snap
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/form-controls.test.js
Labels: enhancement

#5 Added docs for schema definitions.
  README.md
Labels: docs

#10 feat(Validators): Reworked validation behavior.
  .eslintrc
  src/constants/index.js
  src/form-renderer/render-form.js
  src/tests/validators/validator-mapper.test.js
  src/tests/validators/validators.test.js
  src/validators/helpers.js
  src/validators/index.js
  src/validators/messages.js
  src/validators/validator-mapper.js
  src/validators/validators.js
Labels: enhancement

#11 fix(Validators): expose Validators for messages customization.
  src/index.js
Labels: bug

#13 fix(FormControls): Added prop to hide form controls from form.
  src/form-renderer/index.js
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/form-renderer.test.js
Labels: enhancement

#15 Added deploy comment script.
  .travis.yml
  scripts/demo-deploy-comment.sh
Labels: enhancement

#18 fix(Renderer): can now render Class component.
  src/form-renderer/render-form.js
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/__snapshots__/render-form.test.js.snap
Labels: bug

#19 fix(validators): add option for max/min value to not include treshold
  src/tests/validators/validators.test.js
  src/validators/validator-mapper.js
Labels: enhancement
