Repository data-driven-forms/react-form-renderer, pull requests merged in 2019-03, with the labels that each got.

#36 fix(renderForm): adds clearOnUnmount option
  src/form-renderer/index.js
  src/form-renderer/render-form.js
  src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
  src/tests/form-renderer/__snapshots__/form-information.test.js.snap
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/__snapshots__/render-form.test.js.snap
  src/tests/form-renderer/render-form.test.js
Labels: released

#37 fix(FieldProvider): add default formOptions prop to prevent crashes
  src/form-renderer/render-form.js
  src/tests/form-renderer/__snapshots__/render-form.test.js.snap
Labels: bug

#38 fix(FormRenderer): move form options to form context.
  src/form-renderer/array-form-component.js
  src/form-renderer/condition.js
  src/form-renderer/field-provider.js
  src/form-renderer/field-wrapper.js
  src/form-renderer/index.js
  src/form-renderer/render-form.js
  src/form-renderer/renderer-context.js
  src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/__snapshots__/render-form.test.js.snap
  src/tests/form-renderer/array-form-component.test.js
  src/tests/form-renderer/render-form.test.js
Labels: enhancement

#39 fix(initialValue): Added option to add initialValue on field level.
  demo/sandbox.js
  package.json
  src/form-renderer/field-provider.js
  src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
  src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
  src/tests/form-renderer/__snapshots__/render-form.test.js.snap
  src/tests/form-renderer/render-form.test.js
Labels: enhancement
